### PR TITLE
Proposed corrections and revisions

### PR DESCRIPTION
**Pull request by morskyjezek**
Working on preparing to teach from the LC shell lesson and noted a few places where there it seemed like small corrections could help to improve the flow of the text. Conducted while preparing for instructor checkout process. Feel free to reject or accept selectively, just proposing these as small things noted during lesson prep. Thanks!

### CODE REVIEW

**Comment by dakane1** [comment]
I agree with the change where a word is missing but the rest is just word smithing, the old wording isn't wrong and in a few cases you are adding and or deleting things that aren't needed, like removing `journal` when journal is listed in the example, and changing part of a title for part II but then it doesn't match the title for part I.  I need to look at this when I have more time to figure out where the files are conflicting.  

Also, in future if you can please do pull requests per episode.  It's harder to follow the changes when the pull request covers multiple episodes in the lesson.  It helps the maintainers make quicker decisions.

**Comment by morskyjezek** [comment]
Got it. Thanks @dakane1 - I should've checked on the best way to suggest those.

**Comment by dakane1** [comment]
@morskyjezek creating issues is always a great way to go.  Pull requests are great when they are sort of small chunks, easier to check, comment, and merge.  With this one I will spend some time on Friday looking it over and figuring out the conflicts. Some of the things you bring up I might do other pull requests for and some I might not be accepted.  In the mean time lets keep this open so I can refer to it.

**Comment by dakane1** [comment]
Submitted pull request #80 for episode 06-free -test changes.  Will look at Ep. 05 on Monday.

**Comment by dakane1** [comment]
Sorry @morskyjezek I haven't had a chance to get to your other recommendations yet.  I should have some space in my schedule next week.

**Pull request closed without merging**
