### PR TITLE
Fixing typos in examples, additional underscores for loop exercise, p…

### PR DESCRIPTION
**Pull request by elopatin-uc3**
…lus corrected wc output

Please double-check the values that were changed for the `wc -l` output in Ep.5. I'm unsure if these differ per the version of grep on my laptop.

### CODE REVIEW

**Comment by libcce** [comment]
LGTM! Thanks @elopatin-uc3!

**Comment by elopatin-uc3** [comment]
Thanks for the review @libcce!

**Comment by dakane1** [comment]
@elopatin-uc3 @libcce Checked the code and I was getting the same #'s.  All is good :-)

**Comment by elopatin-uc3** [comment]
Thanks @dakane1 :-)

**Pull request merged**
