### PR TITLE
Updated changes to "What is happening in the loop?

### PR DESCRIPTION
**Pull request by scottcpeterson**
Updated changes to "What is happening in the loop?" section to reflect my changes to the loop in pull request #87 when I added -wc to the grep command. I also corrected "What is happening the the loop?" to "What is happening in the loop?".

### CODE REVIEW

**Comment by libcce** [comment]
Thanks @scottcpeterson! It looks like you changed ` to ' which removes the special formatting for the command. Can you add that back? Then I think this is ready to merge.

**Comment by scottcpeterson** [comment]
Hi Chris,

I don't understand what you mean here. I can't see a 'to ' in the changes.

Cheers,

Scott

**Comment by libcce** [comment]
Just a minor change https://github.com/LibraryCarpentry/lc-shell/commit/ca8d0b6b13db69eca8974cbc30341a05da962c7e otherwise the rest was good. Thanks!

**Comment by ostephens** [comment]
Hi @scottcpeterson it was the use of an inverted comma/apostrophe ' in place of a backtick ` that @libcce was commenting on.

I think there's still another one that needs fixing:
`\`$name'`
should be
`\`$name\``

**Comment by libcce** [comment]
Hi @ostephens Thanks! I couldn't remember the name, inverted apostrophe and was just going to say tick 😄 Thanks for the clearer explanation! I've updated the other fixes you mention as well https://github.com/LibraryCarpentry/lc-shell/commit/928913fa4a485d458158851ede1e77e19a88216c. Thanks again @scottcpeterson !

**Comment by ostephens** [comment]
@libcce you've fixed it while I'm still trying to get the syntax in my comment right!

**Comment by scottcpeterson** [comment]
Thanks. Now I understand what you are talking about,

**Pull request merged**
